defaults:
  - approximator@_global_: hypogen
  - reward@_global_: overwrite_all
  - dynamics@_global_: default
  - override hydra/launcher: joblib
  - _self_

# dataset dir
rollout_dir: ./rollout_data
domain_task: LiftCube
# train settings
num_train_epochs: 2000
batch_size: 512
test_fraction: 0.7
# save
save_every_frames: 100
# snapshot
save_snapshot: true
# misc
seed: 2
device: cuda
# experiment
experiment: 'maniskill_exp'
# approximator
input_to_model: 'cube'     # options: 
noise_clip: 0.02
value_weight: 0.00
td_weight: 0.01
hidden_dim: 256
embed_dim: 256
k_shot: 10
adaptation_steps: 5

num_layers: 8
use_norm: true
weight_dim: 128
enc_dec_dim: 256
opt_block_dim: 128
opt_mid_dim: 64
num_opt_mlp_layer: 2
num_enc_dec_layer: 2
dl_din_way: direct
dl_dw_way: direct
mid_act: F.tanh
target_layers_num: 3

approximator:
  use_td: false

AVAILABLE_GPUS: [ 0 ]


hydra:
  job:
    chdir: True
  run:
    dir: ./results_approximator/${experiment}/${approximator_name}/${input_to_model}/${domain_task}/seed_${seed}/
  sweep:
    dir: ./results_approximator/${experiment}/${approximator_name}/${input_to_model}/${domain_task}/seed_${seed}/
    subdir: ""
  sweeper:
    params:
      approximator@_global_: hypogen
      seed: 2
      domain_task: LiftCube, PickCube
      input_to_model: cube, damp, stiff, length
  launcher:
    n_jobs: 15
